### ISSUE TITLE
Thaumcraft Crashes

### ISSUE THREAD

**Issue by SpectacularNumbers** [ZeekDaGeek/worldworldpack-public#11]
When logging into the server, I get this thaumcraft crash: 
http://pastebin.com/8S0G46vd
Looks like its a thaumcraft table, of which I have 3 which I recently made. (2 for research table, 1 for arcane crafting.)
The research table has a research note in it aswell.

**Comment by SpectacularNumbers** [comment]
Any updates?

**Comment by ZeekDaGeek** [comment]
Do you know if the server crashes when you attempt to connect?

**Comment by SpectacularNumbers** [comment]
It does not crash. From what I can tell from the crash log, WALIA is trying to get information about the table, but failing. It maybe because I had a research note inside of the table when I logged out.

:/

**Comment by SpectacularNumbers** [comment]
Fixed It: Went into a single player world and hid the walia GUI, then logged in.
