### ISSUE TITLE
Server crashed my MC

### ISSUE THREAD

**Issue by Charluvsyou** [ZeekDaGeek/worldworldpack-public#12]
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using MaxGCMinorPauseMillis as minor pause goal is deprecatedand will likely be removed in future release
Minecraft exited with exitcode -1.

I tried twice and that's all it does. I am using MultiMC.

**Comment by xXTheBigBearXx** [comment]
A link to the full crash report might be useful

**Comment by Charluvsyou** [comment]
http://paste.ee/p/q7jm4

**Comment by xXTheBigBearXx** [comment]
Thats just the console log :/ The crash report can be found in the instance folder

**Comment by Charluvsyou** [comment]
um... i am not tech savy... so what?

**Comment by xXTheBigBearXx** [comment]
C:/Users/Charlotte/Downloads/mmc-stable-win32/MultiMC/instances/worldworldpack-b0.1.3/minecraft/crash-reports

**Comment by Charluvsyou** [comment]
how am i suposed to link them?

**Comment by xXTheBigBearXx** [comment]
Dropbox?

**Comment by Charluvsyou** [comment]
https://www.dropbox.com/s/ybljx6iyhjzonc7/crash-2015-02-08_09.37.23-client.txt?dl=0

**Comment by xXTheBigBearXx** [comment]
What happens if you go into Singleplayer?

**Comment by Charluvsyou** [comment]
https://www.dropbox.com/s/alzocw56wctwor6/crash-2015-02-08_10.07.38-server.txt?dl=0

**Comment by ZeekDaGeek** [comment]
I don't believe the server is crashing when you connect. I think it's just your client running out of memory.

First off to make sure that Minecraft is able to use more memory ensure that you have the proper version of Java installed.

Go to "C:\Program Files\Java" and take a screenshot of the folder so I can see the versions.
While you're at it also right click on "Computer" in the start menu and take a screenshot of the dialog that pops up which will show your maximum memory.

You can also attempt the following:

In MultiMC:
- Right click on "The World World Pack"
- Go down to "Instance Settings"
- Double the Minimum and Maximum options and try again.

If that doesn't work the minimap is the thing that's using up the memory is your minimap. You can attempt to disable it for the time being:

In MultiMC
- Right click on "The World World Pack"
- Go down to "Edit Instance"
- On the left hand side select "Loader Mods"
- Disable Mapwriter
- Try connecting again.

**Comment by ZeekDaGeek** [comment]
Ticket seems abandoned.
