### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by SpectacularNumbers** [ZeekDaGeek/worldworldpack-public#14]
I'm am crashing on start up and not sure what is causing it, was fine yesterday.

World World Pack (Latest) with Thaumcraft Node Tracker and Thaumcraft NEI Addon. Removing these does not fix the issue.

http://paste.ee/p/nVKUb

**Comment by SpectacularNumbers** [comment]
Any updates?

**Comment by ZeekDaGeek** [comment]
Are you attempting to connect to the server or singleplayer?

SHhh I was in the middle of typing things out.

**Comment by SpectacularNumbers** [comment]
Im not even connecting to anything, its crashing while loading the modpack. Not sure why its including entities..

**Comment by ZeekDaGeek** [comment]
Try removing your player stats seeing as the error is related to that. You want to edit the instance and edit move the following file:

{...}/minecraft/stats/player.uid

**Comment by SpectacularNumbers** [comment]
Deleted player.uid, now getting this crash: 

http://paste.ee/p/cmBKt

Looks like gany's nether is trying to do something. (It is erroring on startup)

**Comment by SpectacularNumbers** [comment]
Got it to work, turns out the download I got had a bad version of Gany's Nether.
