### ISSUE TITLE
Version 0.2.0 prerelease

### ISSUE THREAD

**Issue by ZeekDaGeek** [ZeekDaGeek/worldworldpack-public#16]
There are potentially issues with version 0.2.0. I need to know if you are able to load your previously created worlds with this version. Let me know if it works, let me know if it doesn't work and what error you get. (Should be something related to level.dat backup being inaccessible)

Prerelease download:

**Comment by Orlando1999** [comment]
Hi Zeek, got the world to load with a message that i should backup level.dat. After loading the world a lot of blocks/machines were changed to other blocks/machines.

**Comment by xXTheBigBearXx** [comment]
Started to load world, was given a warning about the level.dat backup, but then the pack crashed. World worked fine on previous version of the pack. "Server" Crash Report: https://www.dropbox.com/s/873vyeiae9aqq5w/crash-2015-03-07_12.58.21-server.txt?dl=0
Client Crash Report: https://www.dropbox.com/s/76vxcv7nrph3kbr/crash-2015-03-07_12.59.26-client.txt?dl=0

**Comment by ZeekDaGeek** [comment]
Official releases are now out.

Update to 0.1.8, run your world and then update to 0.2.0. It should work.
