### ISSUE TITLE
wwpack launching error

### ISSUE THREAD

**Issue by miguelfdsc** [ZeekDaGeek/worldworldpack-public#19]
when i try to open the world world pack on the ftb launcher, it opens minecraft vanilla, I dont know what to do to play the pack.
Can someone help me??

**Comment by ZeekDaGeek** [comment]
Not much information has been provided so let me go through each step.
1. You've downloaded the FTB launcher (EXE) from http://www.feed-the-beast.com/
2. Once opened you selected "3RD PARTY PACKS" on the top.
3. You clicked on "Pack Codes" in the top right and entered "wwpack" and clicked add.
4. You scrolled down the "3RD PARTY PACKS" list and selected "The World World Pack (v.2.x)" from the list and pressed "Launch" with the correct user information selected?

If all of these things have been done let me know.

**Comment by miguelfdsc** [comment]
Yes, I've done all that.

2015-03-22 21:01 GMT+00:00 ZeekDaGeek notifications@github.com:

**Comment by miguelfdsc** [comment]
help...

**Comment by ZeekDaGeek** [comment]
I would suggest deleting the instance folder for the World World pack, once you've done that redownload the pack and it should work fine.

**Comment by miguelfdsc** [comment]
Thanks, I will try that
