### ISSUE TITLE
Ender Tank Recipe Crash

### ISSUE THREAD

**Issue by xXTheBigBearXx** [ZeekDaGeek/worldworldpack-public#20]
If I try to look at the recipe for the Ender Tank (Ender Storage) My game freezes then crashes.

Here is the crash report: https://www.dropbox.com/s/x4k8b9q3c8mkfy8/crash-2015-04-13_18.39.45-client.txt?dl=0

**Comment by ZeekDaGeek** [comment]
Crash related to NEI Integration, fixed in newer version, and will be fixed in the next pack update.
