### ISSUE TITLE
Enderletter Crash

### ISSUE THREAD

**Issue by Wanuy** [ZeekDaGeek/worldworldpack-public#21]
When I open a letter for the first time it freezes and crashed my client.

**Comment by xXTheBigBearXx** [comment]
This crash is not so much "The first time" but just randomly

**Comment by Wanuy** [comment]
I just noticed it happened when I open a letter for the first time

**Comment by ZeekDaGeek** [comment]
Is it based on the contents of the letter?

**Comment by Wanuy** [comment]
It's before you've put stuff in
