### ISSUE TITLE
Funky Locomotion Crash

### ISSUE THREAD

**Issue by TymonDomanko** [ZeekDaGeek/worldworldpack-public#24]
I crash occasionally when in a Mystcraft Age and i believe  Funky Locomotion is responsible.
Crash reports follow:
http://pastebin.com/TxPMm9LS
http://pastebin.com/pwVdTX8u
http://pastebin.com/PXaeCVr8
http://pastebin.com/seUUMbcH

**Comment by ZeekDaGeek** [comment]
Try sticking a ChickenChunks loader onto the whole creation it might be that the dimension is not being loaded before it's referenced.

**Comment by TymonDomanko** [comment]
as far as i know there was no frames in the world

**Comment by ZeekDaGeek** [comment]
Let me know if this problem reoccurs in the newest version of the pack, 0.3.0
