### ISSUE TITLE
Loading?

### ISSUE THREAD

**Issue by JCBurnside** [ZeekDaGeek/worldworldpack-public#27]
I can get the pack to load up to ZTones in the phase 1 initialization.  Then my game freezes.

**Comment by xXTheBigBearXx** [comment]
Have you left it or do you instantly close it?

**Comment by JCBurnside** [comment]
I left it running for half an hour once (after disabling a couple of mods) and it still didn't work

**Comment by JCBurnside** [comment]
Ok so I upgraded my ram in my laptop (doubled it from 4 to 8 gigs.) and now it works fine.

**Comment by JCBurnside** [comment]
Nevermind. It got to the final phase then froze again.
