### ISSUE TITLE
Mekanism cardboard box can move things it shouldn't

### ISSUE THREAD

**Issue by Zero9o1o** [ZeekDaGeek/worldworldpack-public#3]
The blacklist for the Mekanism cardboard box hasn't been changed and thus it can move thing from thaumcraft and causes unintended effect.
the ability to move warded block (might want to fix soon)
the ability to move nodes and when a node is moved the data of the node changes.

A fix would be to blacklist thaumcraft from the cardboard box

**Comment by ZeekDaGeek** [comment]
Mekanism blacklist seems broken at the moment. Will revisit this when it's fixed.
