### ISSUE TITLE
Server doesnt work 

### ISSUE THREAD

**Issue by Quxiii** [ZeekDaGeek/worldworldpack-public#31]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 06.06.15 14:35
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: Better Title Screen is a client-side only mod
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:76)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: Better Title Screen is a client-side only mod
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    ... 28 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1206383696 bytes (1150 MB) / 2077753344 bytes (1981 MB) up to 3151495168 bytes (3005 MB)
    JVM Flags: 5 total; -Xms2048m -Xmx3072m -XX:PermSize=256m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 182 mods loaded, 182 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.10.99.99} [Forge Mod Loader](FTBServer-1.7.10-1408.jar) Unloaded->Constructed
    Forge{10.13.3.1408} [Minecraft Forge](FTBServer-1.7.10-1408.jar) Unloaded->Constructed
    appliedenergistics2-core{rv2-stable-3} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed
    CodeChickenCore{1.0.6.44} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed
    MobiusCore{1.2.5} [MobiusCore](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.4.107} [Not Enough Items](notenoughitems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) Unloaded->Constructed
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed
    OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) Unloaded->Constructed
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed
    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed
    FloatingRuins{1.7.10.r02} [FloatingRuins]([1.7.10]floatingruins-universal-1.7.10.r02.jar) Unloaded->Constructed
    AgriCraft{1.7.10-1.3.1} [AgriCraft](agricraft-1.7.10-1.3.1.jar) Unloaded->Constructed
    animalbikes{1.7.10} [Animal Bikes](animalbikes_1.7.10.jar) Unloaded->Constructed
    AppleCore{1.1.0} [AppleCore](applecore-mc1.7.10-1.1.0.jar) Unloaded->Constructed
    appliedenergistics2{rv2-stable-3} [Applied Energistics 2](appliedenergistics2-rv2-stable-3.jar) Unloaded->Constructed
    CoFHCore{1.7.10R3.0.2} [CoFH Core](cofhcore-[1.7.10]3.0.2-282.jar) Unloaded->Constructed
    asielib{0.4.1} [asielib](asielib-1.7.10-0.4.1.jar) Unloaded->Constructed
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed
    bdlib{1.7.1.71} [BD Lib](bdlib-mc1710-1.7.1.71.jar) Unloaded->Constructed
    BetterTitleScreen{1.7.10-1.1} [Better Title Screen](bettertitlescreen-1.7.10-1.1.jar) Unloaded->Errored
    BiblioCraft{1.10.4} [BiblioCraft](bibliocraft[v1.10.4][mc1.7.10].jar) Unloaded->Constructed
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](biomesoplenty-1.7.10-2.1.0.1283-universal.jar) Unloaded->Constructed
    BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](bibliowoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed
    IC2{2.2.722-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.722-experimental.jar) Unloaded->Constructed
    BuildCraft|Core{6.4.15} [BuildCraft](buildcraft-6.4.15.jar) Unloaded->Constructed
    Forestry{3.5.6.15} [Forestry for Minecraft](forestry_1.7.10-3.5.6.15.jar) Unloaded->Constructed
    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](bibliowoods[Forestry][v1.7].jar) Unloaded->Constructed
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](bibliowoods[Natura][v1.5].jar) Unloaded->Constructed
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](thermalfoundation-[1.7.10]1.0.0-85.jar) Unloaded->Constructed
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](thermalexpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed
    BigReactors{0.4.3A} [Big Reactors](bigreactors-0.4.3A.jar) Unloaded->Constructed
    BinnieCore{2.0-pre8} [Binnie Core](binnie-mods-2.0-pre8.jar) Unloaded->Constructed
    Botany{2.0-pre8} [Botany](binnie-mods-2.0-pre8.jar) Unloaded->Constructed
    ExtraBees{2.0-pre8} [Extra Bees](binnie-mods-2.0-pre8.jar) Unloaded->Constructed
    ExtraTrees{2.0-pre8} [Extra Trees](binnie-mods-2.0-pre8.jar) Unloaded->Constructed
    Genetics{2.0-pre8} [Genetics](binnie-mods-2.0-pre8.jar) Unloaded->Constructed
    AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry](bloodmagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
    Thaumcraft{4.2.3.5} [Thaumcraft](thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed
    Botania{r1.6-190} [Botania](botania-r1.6-190.jar) Unloaded->Constructed
    BuildCraft|Builders{6.4.15} [BC Builders](buildcraft-6.4.15.jar) Unloaded->Constructed
    BuildCraft|Energy{6.4.15} [BC Energy](buildcraft-6.4.15.jar) Unloaded->Constructed
    BuildCraft|Factory{6.4.15} [BC Factory](buildcraft-6.4.15.jar) Unloaded->Constructed
    BuildCraft|Transport{6.4.15} [BC Transport](buildcraft-6.4.15.jar) Unloaded->Constructed
    BuildCraft|Silicon{6.4.15} [BC Silicon](buildcraft-6.4.15.jar) Unloaded->Constructed
    CarpentersBlocks{3.3.6} [Carpenter's Blocks](carpenters-blocks-v3.3.6-mc 1.7.10.jar) Unloaded->Constructed
    ChickenChunks{1.3.4.19} [ChickenChunks](chickenchunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed
    Railcraft{9.6.1.0} [Railcraft](railcraft_1.7.10-9.6.1.0.jar) Unloaded->Constructed
    TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed
    ForgeMultipart{1.1.2.334} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
    chisel{2.3.10.37} [Chisel 2](chisel2-2.3.10.37.jar) Unloaded->Constructed
    EnderStorage{1.4.7.36} [EnderStorage](enderstorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed
    MineFactoryReloaded{1.7.10R2.8.1B1} [MineFactory Reloaded](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MrTJPCoreMod{1.0.7.14} [MrTJPCore](MrTJPCore-1.0.7.14-universal.jar) Unloaded->Constructed
    ProjRed|Core{4.6.1.80} [ProjectRed](projectred-1.7.10-4.6.1.80-base.jar) Unloaded->Constructed
    ProjRed|Transmission{4.6.1.80} [ProjectRed-Transmission](projectred-1.7.10-4.6.1.80-integration.jar) Unloaded->Constructed
    OpenComputers{1.5.11.25} [OpenComputers](opencomputers-mc1.7.10-1.5.11.25-universal.jar) Unloaded->Constructed
    Waila{1.5.10} [Waila](waila-1.5.10_1.7.10.jar) Unloaded->Constructed
    CompactMachines{1.7.10-1.19b} [Compact Machines](compactmachines-1.7.10-1.19b.jar) Unloaded->Constructed
    GalacticraftCore{3.0.12} [Galacticraft Core](galacticraftcore-1.7-3.0.12.339.jar) Unloaded->Constructed
    Mekanism{8.1.2} [Mekanism](mekanism-1.7.10-8.1.2.229.jar) Unloaded->Constructed
    EnderIO{1.7.10-2.3.0.385_beta} [Ender IO](enderio-1.7.10-2.3.0.385_beta.jar) Unloaded->Constructed
    computronics{1.5.1} [Computronics](computronics-1.7.10-1.5.1.jar) Unloaded->Constructed
    DraconicEvolution{1.0.1c} [Draconic Evolution](draconic-evolution-1.7.10-1.0.1c.jar) Unloaded->Constructed
    eirairc{2.8.215} [EiraIRC](eirairc-mc1.7.10-2.8.215.jar) Unloaded->Constructed
    Enchiridion{1.1} [Enchiridion](enchiridion2-1.7.10-2.0.1.jar) Unloaded->Constructed
    Enchiridion2{2.0.1} [Enchiridion 2](enchiridion2-1.7.10-2.0.1.jar) Unloaded->Constructed
    EnderTech{1.7.10-0.3.2.388} [EnderTech](endertech-1.7.10-0.3.2.388.jar) Unloaded->Constructed
    enhancedportals{3.0.10} [EnhancedPortals](enhancedportals_1.7.10-universal-3.0.10.jar) Unloaded->Constructed
    ExtraUtilities{1.2.4c} [Extra Utilities](extrautilities-1.2.4c.jar) Unloaded->Constructed
    factorization.notify{1.0} [Factorization Notification System](factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
    factorization{1.7.10-0.8.88.7} [Factorization](factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
    factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense](factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed
    FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) Unloaded->Constructed
    FlatSigns{2.1.0.19} [Flat Signs](flatsigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed
    Steamcraft{0.28.7} [Flaxbeard's Steam Power](flaxbeardssteampower-1.7.10-0.28.7.jar) Unloaded->Constructed
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](thaumictinkerer-2.5-1.7.10-164.jar) Unloaded->Constructed
    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](forbidden-magic-1.7.10-0.562.jar) Unloaded->Constructed
    funkylocomotion{1.0} [Funky Locomotion](funky-locomotion-1.7.10-beta-5c.jar) Unloaded->Constructed
    GalacticraftMars{3.0.12} [Galacticraft Planets](galacticraft-planets-1.7-3.0.12.339.jar) Unloaded->Constructed
    ganysend{1.9.0} [Gany's End](ganys-end-1.9.0.jar) Unloaded->Constructed
    ganysnether{1.8.0} [Gany's Nether](ganys-nether-1.8.0.jar) Unloaded->Constructed
    ganyssurface{1.11.0} [Gany's Surface](ganys-surface-1.11.0.jar) Unloaded->Constructed
    TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](tconstruct-1.7.10-1.8.5.jar) Unloaded->Constructed
    MagicBees{1.7.10-2.1.22} [Magic Bees](magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed
    gendustry{1.4.10.77} [GenDustry](gendustry-mc1710-1.4.10.77.jar) Unloaded->Constructed
    HardcoreEnderExpansion{1.8.1} [Hardcore Ender Expansion](hardcoreenderexpansion-mc-1.7.10-v1.8.1-beta.jar) Unloaded->Constructed
    iChunUtil{4.1.3} [iChunUtil](ichunutil-4.1.3.jar) Unloaded->Constructed
    Hats{4.0.1} [Hats](hats-4.0.1.jar) Unloaded->Constructed
    HatStand{4.0.0} [HatStand](hatstand-4.0.0.jar) Unloaded->Constructed
    IGWMod{1.1.1-17} [In-Game wiki Mod](igw-mod.jar) Unloaded->Constructed
    inpure|core{1.7.10R1.0.0B9} [INpureCore](inpurecore-[1.7.10]1.0.0b9-62.jar) Unloaded->Constructed
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](inventorytweaks-1.59-dev-152.jar) Unloaded->Constructed
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
    ItemSearch{1.4.0} [Briman's Item Search](itemsearch-1.4.0.jar) Unloaded->Constructed
    JABBA{1.2.1} [JABBA](jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed
    Mariculture{1.7.10-1.2.4.2a} [Mariculture](mariculture-deluxe-1.7.10-1.2.4.2a.jar) Unloaded->Constructed
    MariTech{1.0} [Marine Technlogy](mariculture-deluxe-1.7.10-1.2.4.2a.jar) Unloaded->Constructed
    MekanismGenerators{8.1.2} [MekanismGenerators](mekanismgenerators-1.7.10-8.1.2.229.jar) Unloaded->Constructed
    MekanismTools{8.1.2} [MekanismTools](mekanismtools-1.7.10-8.1.2.229.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1B1} [MFR Compat: Applied Energistics](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.1B1} [MFR Compat: Atum](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1B1} [MFR Compat: BackTools](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1B1} [MFR Compat: BuildCraft](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1B1} [MFR Compat: Chococraft](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1B1} [MFR Compat: ExtraBiomes](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.1B1} [MFR Compat: Forestry](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1B1} [MFR Compat: ForgeMicroblock](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.1B1} [MFR Compat: IC2](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    Mystcraft{0.11.9.03} [Mystcraft](mystcraft-1.7.10-0.11.9.03.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.1B1} [MFR Compat: Mystcraft](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    ProjRed|Exploration{4.6.1.80} [ProjectRed-Exploration](projectred-1.7.10-4.6.1.80-world.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1B1} [MFR Compat ProjectRed](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1B1} [MFR Compat: Railcraft](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1B1} [MFR Compat: Sufficient Biomes](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1B1} [MFR Compat: Thaumcraft](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1B1} [MFR Compat: Thermal Expansion](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1B1} [MFR Compat: Tinkers' Construct](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1B1} [MFR Compat: TwilightForest](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1B1} [MFR Compat: Vanilla](minefactoryreloaded-[1.7.10]2.8.1b1-113.jar) Unloaded->Constructed
    MineTweaker3{3.0.9B} [MineTweaker 3](minetweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed
    modtweaker2{0.7} [Mod Tweaker 2](modtweaker2-0.7.3.jar) Unloaded->Constructed
    morechisels{@VERSION@} [More Chisels](morechisels-1.7.10-1.0-20.jar) Unloaded->Constructed
    NEIAddons{1.12.8.29} [NEI Addons](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons|AppEng{1.12.8.29} [NEI Addons: Applied Energistics 2](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons|Botany{1.12.8.29} [NEI Addons: Botany](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons|Forestry{1.12.8.29} [NEI Addons: Forestry](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons|CraftingTables{1.12.8.29} [NEI Addons: Crafting Tables](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    NEIAddons|ExNihilo{1.12.8.29} [NEI Addons: Ex Nihilo](neiaddons-1.12.8.29-mc1.7.10.jar) Unloaded->Constructed
    neiintegration{1.0.9} [NEI Integration](neiintegration-mc1.7.10-1.0.9.jar) Unloaded->Constructed
    notenoughkeys{@MOD_VERSION@} [NotEnoughKEys](notenoughkeys-1.7.10-1.0.0b29.jar) Unloaded->Constructed
    ObsidiPlates{3.0.0.18} [ObsidiPlates](obsidiplates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed
    OpenMods{0.7.3} [OpenMods](openmodslib-1.7.10-0.7.3-snapshot-362.jar) Unloaded->Constructed
    OpenBlocks{1.4.3} [OpenBlocks](openblocks-1.7.10-1.4.3-snapshot-637.jar) Unloaded->Constructed
    MapWriter{2.1.2} [MapWriter](opis-1.2.5_1.7.10.jar) Unloaded->Constructed
    Opis{1.2.5} [Opis](opis-1.2.5_1.7.10.jar) Unloaded->Constructed
    harvestcraft{1.7.10g} [Pam's HarvestCraft](pams-harvestcraft-1.7.10h.jar) Unloaded->Constructed
    PneumaticCraft{1.6.4-66} [PneumaticCraft](pneumaticcraft-1.7.10-1.6.4-66-universal.jar) Unloaded->Constructed
    ProjRed|Transportation{4.6.1.80} [ProjectRed-Transportation](projectred-1.7.10-4.6.1.80-mechanical_beta.jar) Unloaded->Constructed
    ProjRed|Compatibility{4.6.1.80} [ProjectRed-Compatibility](projectred-1.7.10-4.6.1.80-compat.jar) Unloaded->Constructed
    ProjRed|Integration{4.6.1.80} [ProjectRed-Integration](projectred-1.7.10-4.6.1.80-integration.jar) Unloaded->Constructed
    ProjRed|Illumination{4.6.1.80} [ProjectRed-Illumination](projectred-1.7.10-4.6.1.80-lighting.jar) Unloaded->Constructed
    ProjRed|Expansion{4.6.1.80} [ProjectRed-Expansion](projectred-1.7.10-4.6.1.80-mechanical_beta.jar) Unloaded->Constructed
    RandomThings{2.2.4} [Random Things](randomthings-2.2.4.jar) Unloaded->Constructed
    RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](redstonearsenal-[1.7.10]1.1.0-83.jar) Unloaded->Constructed
    RefinedRelocation{1.0.8b} [Refined Relocation](refinedrelocation-1.7.10-1.0.8b.jar) Unloaded->Constructed
    libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) Unloaded->Constructed
    xreliquary{1.2} [Reliquary](reliquary-1.2.257.jar) Unloaded->Constructed
    RIO{2.3} [RemoteIO](remoteio-1.7.10-2.3.b0-universal.jar) Unloaded->Constructed
    simplyjetpacks{1.4.1} [Simply Jetpacks](simplyjetpacks-mc1.7.10-1.4.1.jar) Unloaded->Constructed
    Squeedometer{1.0.3} [Squeedometer](squeedometer-mc1.7.x-1.0.3.jar) Unloaded->Constructed
    StevesCarts{2.0.0.b18} [Steve's Carts 2](stevescarts2.0.0.b18.jar) Unloaded->Constructed
    StevesFactoryManager{A93} [Steve's Factory Manager](stevesfactorymanagerA93.jar) Unloaded->Constructed
    StevesWorkshop{0.5.0} [Steve's Workshop](stevesworkshop-0.5.0.jar) Unloaded->Constructed
    symcalc{0.13.5} [Symcalc](symcalc-0.13.5.jar) Unloaded->Constructed
    thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed
    ThaumicExploration{0.6.0} [Thaumic Exploration](thaumicexploration-1.7.10-1.1-37.jar) Unloaded->Constructed
    thaumicinfusion{4.002} [Thaumic Infusion](thaumicinfusion-4.jar) Unloaded->Constructed
    TKE{2.3.5} [The Kappa Experience](thekappaexperience-1.7.10-2.3.5.jar) Unloaded->Constructed
    ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics](thermaldynamics-[1.7.10]1.0.0-129.jar) Unloaded->Constructed
    TiCTooltips{1.2.4} [TiC Tooltips](tictooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed
    TMechworks{0.2.14.100} [Tinkers' Mechworks](tmechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed
    TrailMix{4.0.0} [TrailMix](trailmix-4.0.0.jar) Unloaded->Constructed
    Translocator{1.1.1.14} [Translocator](translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed
    WailaHarvestability{1.1.1} [Waila Harvestability](wailaharvestability-mc1.7.x-1.1.1.jar) Unloaded->Constructed
    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) Unloaded->Constructed
    WR-CBE|Core{1.4.1.9} [WR-CBE Core](wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](wr-cbe-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed
    Ztones{1.7.10} [Ztones](ztones-1.7.10-2.2.1.jar) Unloaded->Constructed
    McMultipart{1.1.2.334} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
    aobd{2.6.2} [Another One Bites The Dust](aobd-2.6.2.jar) Unloaded->Constructed
    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) Unloaded->Constructed
    IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](iguanatinkertweaks-1.7.10-2.1.5.jar) Unloaded->Constructed
    technom{0.10.0} [Technomancy](technomancy-0.10.k-1.7.10.jar) Unloaded->Constructed
    ForgeMicroblock{1.1.2.334} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.334-universal.jar) Unloaded->Constructed
    OpenModsLib class transformers: [gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED],[map_gen_fix:ENABLED],[movement_callback:ENABLED],[stencil_patches:ENABLED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-3 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-282
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-85
    ThermalExpansion: -[1.7.10]4.0.1-182
    MineFactoryReloaded: -[1.7.10]2.8.1B1-113
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.0-83
    ThermalDynamics: -[1.7.10]1.0.0-129
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by ZeekDaGeek** [comment]
Go through the mods and remove client side mods such as InventoryTweaks.
