### ISSUE TITLE
Duplicate Recipe

### ISSUE THREAD

**Issue by Zero9o1o** [ZeekDaGeek/worldworldpack-public#34]
The blood magic book has a recipe already.. you get it by tossing a mail order catalog on the ground but zeekdageek added a recipe for some weird reason.

**Comment by ZeekDaGeek** [comment]
Until recently the Blood magic page has clear stated that it did not have a recipe for the book and you needed to spawn it in, which is what chat told to me as well. Deleted the recipe now.
