### ISSUE TITLE
Crash reason

### ISSUE THREAD

**Issue by Nitrodev** [ZeekDaGeek/worldworldpack-public#35]
Exception in thread "AE2 VersionChecker" AL lib: (EE) alc_cleanup: 1 device not closed

That appears on the mmc log after the game is finished loading, resulting in a crash.

**Comment by ZeekDaGeek** [comment]
Can I get the full crash log?

**Comment by Nitrodev** [comment]
Okay looks like it works now, i just reinstalled the pack and it works just fine
