### ISSUE TITLE
Corrupt files in 0.4.0a

### ISSUE THREAD

**Issue by khumps** [ZeekDaGeek/worldworldpack-public#38]
When trying to download the zip it downloaded successfully. however when i tried to unzip it mekanism(main mod only) and modtweaker could not be unzipped. i went and found the respective files on the developers websites and swapped them in the zip and the thing unzips fine now.

**Comment by ZeekDaGeek** [comment]
After restarting the server it seems like the corrupt downloads are fixed. Additionally 0.5.0 is available.

http://tinyurl.com/wwpack
