### ISSUE TITLE
Server crashes, client works

### ISSUE THREAD

**Issue by khumps** [ZeekDaGeek/worldworldpack-public#39]
I am trying to start the server and it is crashing.
http://hastebin.com/uragazuzas.avrasm
More of the log
http://hastebin.com/inonixuseb.vbs

**Comment by ZeekDaGeek** [comment]
It appears the packed version of PneumaticCraft has issues with Mekanism as stated in the changelog for the next version:

http://minecraft.curseforge.com/projects/pneumaticcraft/files/2259497

Updating to any of the newer versions of PneumaticCraft should fix the issues: http://minecraft.curseforge.com/projects/pneumaticcraft/files

I'll work on an update.

**Comment by khumps** [comment]
tried the next version and it worked. Thanks!
