### ISSUE TITLE
Crash on Messing with it

### ISSUE THREAD

**Issue by Zero9o1o** [ZeekDaGeek/worldworldpack-public#5]
Apothecary Cauldron from Xeno's Reliquary.
You can't place it with out crashing.
You can't break it with out crashing.
You can't cardboard box it with out crashing.

**Comment by Zero9o1o** [comment]
You can destroy it with a terra shatterer from botania to break it

**Comment by ZeekDaGeek** [comment]
Try it in the newest version.
