### ISSUE TITLE
Crash while using NEI

### ISSUE THREAD

**Issue by xXTheBigBearXx** [ZeekDaGeek/worldworldpack-public#8]
https://www.dropbox.com/s/39ymy46aolj2u52/crash-2015-01-22_18.04.30-client.txt?dl=0

Is a link to my crash report ^

**Comment by xXTheBigBearXx** [comment]
After crashing again, it turns out pressing 'U' on any Botania flower crashes out of the client.

**Comment by xXTheBigBearXx** [comment]
Its the Osmotic Enchanters Turn! https://www.dropbox.com/s/mseq2kogegpkuiz/crash-2015-01-23_19.56.11-client.txt?dl=0

**Comment by ZeekDaGeek** [comment]
Remove EE3 to fix the first problem.

Second problem should be fixed in this next update.
